### ISSUE TITLE
build_exe fails if there are specific versions in install_requires

### ISSUE THREAD

**Issue by xmikos** [xoviat/subzero#61]
If I have versions specified in `install_requires` for some dependencies, build_exe fails. I had to remove specific versions to make it work. Example (from my [QSpectrumAnalyzer](https://github.com/xmikos/qspectrumanalyzer)):

```
    install_requires=[
        "soapy_power>=1.5.0",
        "pyqtgraph>=0.10.0",
        "Qt.py"
    ],
```

Errors:
```markdown
$ python setup.py bdist_msi
/    Installing project requirements...
running bdist_msi
running build_exe
running build
running build_py
creating build\lib
creating build\lib\qspectrumanalyzer

copying qspectrumanalyzer\plot.py -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\ui_qspectrumanalyzer.py -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\ui_qspectrumanalyzer_colors.py -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\ui_qspectrumanalyzer_persistence.py -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\ui_qspectrumanalyzer_settings.py -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\ui_qspectrumanalyzer_settings_help.py -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\ui_qspectrumanalyzer_smooth.py -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\utils.py -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\version.py -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\__init__.py -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\__main__.py -> build\lib\qspectrumanalyzer
creating build\lib\qspectrumanalyzer\backends
copying qspectrumanalyzer\backends\hackrf_sweep.py -> build\lib\qspectrumanalyzer\backends
copying qspectrumanalyzer\backends\rtl_power.py -> build\lib\qspectrumanalyzer\backends
copying qspectrumanalyzer\backends\rtl_power_fftw.py -> build\lib\qspectrumanalyzer\backends
copying qspectrumanalyzer\backends\rx_power.py -> build\lib\qspectrumanalyzer\backends
copying qspectrumanalyzer\backends\soapy_power.py -> build\lib\qspectrumanalyzer\backends
copying qspectrumanalyzer\backends\__init__.py -> build\lib\qspectrumanalyzer\backends
copying qspectrumanalyzer\qspectrumanalyzer.ui -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\qspectrumanalyzer_colors.ui -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\qspectrumanalyzer_persistence.ui -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\qspectrumanalyzer_settings.ui -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\qspectrumanalyzer_settings_help.ui -> build\lib\qspectrumanalyzer
copying qspectrumanalyzer\qspectrumanalyzer_smooth.ui -> build\lib\qspectrumanalyzer
creating build\lib\qspectrumanalyzer\languages
copying qspectrumanalyzer\languages\qspectrumanalyzer_cs.qm -> build\lib\qspectrumanalyzer\languages
copying qspectrumanalyzer\languages\qspectrumanalyzer_cs.ts -> build\lib\qspectrumanalyzer\languages
running build_scripts
copying build\temp.win-amd64-3.6\QSpectrumAnalyzer.py -> build\scripts-3.6
copying build\temp.win-amd64-3.6\soapy_power.py -> build\scripts-3.6
**Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 20, in walk_packages
  File "C:\Users\mikos\Downloads\qspectrumanalyzer.new2\qspectrumanalyzer\backends\__init__.py", line 112, in <module>
    from qspectrumanalyzer.backends import soapy_power, hackrf_sweep, rtl_power, rtl_power_fftw, rx_power
  File "C:\Users\mikos\Downloads\qspectrumanalyzer.new2\qspectrumanalyzer\backends\soapy_power.py", line 9, in <module>
    from soapypower.writer import SoapyPowerBinFormat
  File "C:\Program Files\Python36\lib\site-packages\soapypower\writer.py", line 7, in <module>
    from soapypower import threadpool
  File "C:\Program Files\Python36\lib\site-packages\soapypower\threadpool.py", line 1, in <module>
    import os, queue, concurrent.futures
  File "C:\Program Files\Python36\lib\site-packages\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "C:\Program Files\Python36\lib\site-packages\concurrent\futures\_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax**
1925 INFO: wrote C:\Users\mikos\Downloads\qspectrumanalyzer.new2\build\temp.win-amd64-3.6\QSpectrumAnalyzer.spec
1942 INFO: UPX is not available.
1942 INFO: Extending PYTHONPATH with paths
['C:\\Users\\mikos\\Downloads\\qspectrumanalyzer.new2\\build\\temp.win-amd64-3.6',
 'C:\\Users\\mikos\\Downloads\\qspectrumanalyzer.new2\\build\\lib',
 'C:\\Users\\mikos\\Downloads\\qspectrumanalyzer.new2\\build\\temp.win-amd64-3.6',
 'C:\\Users\\mikos\\Downloads\\qspectrumanalyzer.new2\\build\\temp.win-amd64-3.6']
1942 INFO: checking Analysis
1942 INFO: Building Analysis because out00-Analysis.toc is non existent
1942 INFO: Initializing module dependency graph...
1942 INFO: Initializing module graph hooks...
1942 INFO: Analyzing base_library.zip ...
5723 INFO: Analyzing hidden import 'soapy_power>=1.5.0'
**5723 ERROR: Hidden import 'soapy_power>=1.5.0' not found**
5723 INFO: Analyzing hidden import 'pyqtgraph>=0.10.0'
5723 ERROR: Hidden import 'pyqtgraph>=0.10.0' not found
5723 INFO: Analyzing hidden import 'Qt.py'
5860 INFO: Processing pre-find module path hook   PyQt5.uic.port_v3
5878 INFO: Processing pre-find module path hook   PyQt5.uic.port_v2
**6101 ERROR: Hidden import 'Qt.py' not found**
6101 INFO: Analyzing hidden import 'qspectrumanalyzer'
6153 INFO: Analyzing hidden import 'qspectrumanalyzer.\_\_main\_\_'
6943 INFO: Processing pre-find module path hook   distutils
8198 INFO: Processing pre-safe import module hook   six.moves
8731 INFO: Processing pre-safe import module hook   win32com
9075 INFO: Processing pre-find module path hook   site
9075 INFO: site: retargeting to fake-dir 'C:\\Program Files\\Python36\\lib\\site-packages\\PyInstaller\\fake-modules'
13657 INFO: running Analysis out00-Analysis.toc
13657 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Program Files\Python36\python.exe
14012 INFO: Caching module hooks...
14012 INFO: Analyzing C:\Users\mikos\Downloads\qspectrumanalyzer.new2\build\temp.win-amd64-3.6\QSpectrumAnalyzer.py.89f76f67-12b6-4296-98ae-762ce640e072.py
**Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    cmdclass=setup_cmdclass,
  File "C:\Program Files\Python36\lib\site-packages\subzero\__init__.py", line 57, in setup
    distutils_setup(**attrs)
  File "C:\Program Files\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python36\lib\site-packages\subzero\windist.py", line 310, in run
    self.run_command('build_exe')
  File "C:\Program Files\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python36\lib\site-packages\subzero\dist.py", line 182, in run
    self._freeze(executable, self.build_temp, self.build_exe)
  File "C:\Program Files\Python36\lib\site-packages\subzero\dist.py", line 330, in _freeze
    PyInstaller.__main__.run_build(None, spec_file, noconfirm=True, workpath=workpath, distpath=distpath)
  File "C:\Program Files\Python36\lib\site-packages\PyInstaller\__main__.py", line 45, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, \*\*kwargs)
  File "C:\Program Files\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Program Files\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Program Files\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "C:\Program Files\Python36\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "C:\Program Files\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 413, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "C:\Program Files\Python36\lib\site-packages\PyInstaller\depend\analysis.py", line 196, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "C:\Program Files\Python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1386, in run_script
    co_ast = compile(contents, pathname, 'exec', ast.PyCF_ONLY_AST, True)
  File "C:\Users\mikos\Downloads\qspectrumanalyzer.new2\build\temp.win-amd64-3.6\QSpectrumAnalyzer.py.89f76f67-12b6-4296-98ae-762ce640e072.py", line 5
    import soapy_power>=1.5.0
                       ^
SyntaxError: invalid syntax**
```

**Comment by xoviat** [comment]
This is lord63/py-spin#12.

To resolve,

```
pip uninstall -y futures
```

**Comment by xoviat** [comment]
Actually, on second thought, not a duplicat.e

**Comment by xmikos** [comment]
I don't have `futures` installed

**Comment by xoviat** [comment]
> I don't have futures installed

Yes you do. Subzero installed it because it depends on py-spin, which currently has a bug. However, that isn't the only failure.

**Comment by xmikos** [comment]
Btw. that first invalid syntax exception (with concurrent.futures) is something else, I get that even if I remove specific versions of dependencies from `install_requires` (but strangely build works and id finished successfully in that case).

**Comment by xoviat** [comment]
Yes, that's because `futures` is installed.

**Comment by xmikos** [comment]
Really it's not.

```
$ pip list --format columns         
Package          Version            
---------------- ------------------ 
appdirs          1.4.3              
colorama         0.3.7              
contextlib2      0.5.4              
cx-Freeze        5.0.1              
Cython           0.25.2             
decorator        4.0.11             
future           0.16.0             
ipython          5.3.0              
ipython-genutils 0.2.0              
lxml             3.7.3              
numpy            1.12.1             
packaging        16.8               
pathlib          1.0.1              
pickleshare      0.7.4              
pip              9.0.1              
pipdeptree       0.10.1             
prompt-toolkit   1.0.13             
pyFFTW           0.10.4             
Pygments         2.2.0              
PyInstaller      3.3.dev0+g82fb738b 
pypandoc         1.3.3              
pyparsing        2.2.0              
pypiwin32        220                
PyQt5            5.8.1              
pyqtgraph        0.10.0             
PyRTF3           0.46               
pyspin           1.1.0              
pywix            0.1.6              
Qt.py            0.6.9              
setuptools       34.3.3             
simplegeneric    0.8.1              
SimpleSoapy      1.3.0              
SimpleSpectral   1.0.0              
sip              4.19.1             
six              1.10.0             
soapy-power      1.5.0              
subzero          0.2.2+52.g0ff49b3  
traitlets        4.3.2              
wcwidth          0.1.7              
wheel            0.29.0             
```

**Comment by xmikos** [comment]
Ah, I see that now: "C:\Program Files\Python36\lib\site-packages\concurrent\futures\__init__.py"

I don't understand, it must have been somehow installed without pip knowing about it?

**Comment by xmikos** [comment]
(I use concurrent.futures in my code, but that is part of Python standard library)

**Comment by xmikos** [comment]
But the main problem remains - is there are specific versions in `install_requires`, build fails. Somehow code like ` import soapy_power>=1.5.0` get executed in the process, which is invalid syntax.

**Comment by xoviat** [comment]
1. The concurrent.futures problem is related to py-spin
2. The imports problem is a mistake that I made; I will correct it soon.
